// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCastManagerPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCastManagerPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCastManagerPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCastManagerPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCastManagerPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCastManagerPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum ConnectionStatePigeon: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case disconnecting = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastDevicePigeon: Hashable {
  var deviceId: String
  var friendlyName: String
  var modelName: String? = nil
  var statusText: String? = nil
  var deviceVersion: String
  var isOnLocalNetwork: Bool
  var category: String
  var uniqueId: String
  var index: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastDevicePigeon? {
    let deviceId = pigeonVar_list[0] as! String
    let friendlyName = pigeonVar_list[1] as! String
    let modelName: String? = nilOrValue(pigeonVar_list[2])
    let statusText: String? = nilOrValue(pigeonVar_list[3])
    let deviceVersion = pigeonVar_list[4] as! String
    let isOnLocalNetwork = pigeonVar_list[5] as! Bool
    let category = pigeonVar_list[6] as! String
    let uniqueId = pigeonVar_list[7] as! String
    let index: Int64? = nilOrValue(pigeonVar_list[8])

    return CastDevicePigeon(
      deviceId: deviceId,
      friendlyName: friendlyName,
      modelName: modelName,
      statusText: statusText,
      deviceVersion: deviceVersion,
      isOnLocalNetwork: isOnLocalNetwork,
      category: category,
      uniqueId: uniqueId,
      index: index
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      friendlyName,
      modelName,
      statusText,
      deviceVersion,
      isOnLocalNetwork,
      category,
      uniqueId,
      index,
    ]
  }
  static func == (lhs: CastDevicePigeon, rhs: CastDevicePigeon) -> Bool {
    return deepEqualsCastManagerPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastManagerPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastSessionPigeon: Hashable {
  var device: CastDevicePigeon? = nil
  var sessionId: String? = nil
  var connectionState: ConnectionStatePigeon
  var currentDeviceMuted: Bool
  var currentDeviceVolume: Double
  var deviceStatusText: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastSessionPigeon? {
    let device: CastDevicePigeon? = nilOrValue(pigeonVar_list[0])
    let sessionId: String? = nilOrValue(pigeonVar_list[1])
    let connectionState = pigeonVar_list[2] as! ConnectionStatePigeon
    let currentDeviceMuted = pigeonVar_list[3] as! Bool
    let currentDeviceVolume = pigeonVar_list[4] as! Double
    let deviceStatusText = pigeonVar_list[5] as! String

    return CastSessionPigeon(
      device: device,
      sessionId: sessionId,
      connectionState: connectionState,
      currentDeviceMuted: currentDeviceMuted,
      currentDeviceVolume: currentDeviceVolume,
      deviceStatusText: deviceStatusText
    )
  }
  func toList() -> [Any?] {
    return [
      device,
      sessionId,
      connectionState,
      currentDeviceMuted,
      currentDeviceVolume,
      deviceStatusText,
    ]
  }
  static func == (lhs: CastSessionPigeon, rhs: CastSessionPigeon) -> Bool {
    return deepEqualsCastManagerPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastManagerPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StartSessionRequest: Hashable {
  var deviceId: String? = nil
  var deviceIndex: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartSessionRequest? {
    let deviceId: String? = nilOrValue(pigeonVar_list[0])
    let deviceIndex: Int64? = nilOrValue(pigeonVar_list[1])

    return StartSessionRequest(
      deviceId: deviceId,
      deviceIndex: deviceIndex
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      deviceIndex,
    ]
  }
  static func == (lhs: StartSessionRequest, rhs: StartSessionRequest) -> Bool {
    return deepEqualsCastManagerPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastManagerPigeon(value: toList(), hasher: &hasher)
  }
}

private class CastManagerPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionStatePigeon(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CastDevicePigeon.fromList(self.readValue() as! [Any?])
    case 131:
      return CastSessionPigeon.fromList(self.readValue() as! [Any?])
    case 132:
      return StartSessionRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CastManagerPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionStatePigeon {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastDevicePigeon {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CastSessionPigeon {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? StartSessionRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CastManagerPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CastManagerPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CastManagerPigeonPigeonCodecWriter(data: data)
  }
}

class CastManagerPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CastManagerPigeonPigeonCodec(readerWriter: CastManagerPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DiscoveryManagerHostApi {
  func startDiscovery() throws
  func stopDiscovery() throws
  func isDiscoveryActiveForDeviceCategory(deviceCategory: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DiscoveryManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CastManagerPigeonPigeonCodec.shared }
  /// Sets up an instance of `DiscoveryManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DiscoveryManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerHostApi.startDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.startDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerHostApi.stopDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.stopDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let isDiscoveryActiveForDeviceCategoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerHostApi.isDiscoveryActiveForDeviceCategory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDiscoveryActiveForDeviceCategoryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceCategoryArg = args[0] as! String
        do {
          let result = try api.isDiscoveryActiveForDeviceCategory(deviceCategory: deviceCategoryArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDiscoveryActiveForDeviceCategoryChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DiscoveryManagerFlutterApiProtocol {
  func onDevicesChanged(devices devicesArg: [CastDevicePigeon], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DiscoveryManagerFlutterApi: DiscoveryManagerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CastManagerPigeonPigeonCodec {
    return CastManagerPigeonPigeonCodec.shared
  }
  func onDevicesChanged(devices devicesArg: [CastDevicePigeon], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerFlutterApi.onDevicesChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([devicesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SessionManagerHostApi {
  func startSessionWithDevice(request: StartSessionRequest) throws -> Bool
  func endSession() throws -> Bool
  func endSessionAndStopCasting() throws -> Bool
  func setDeviceVolume(value: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SessionManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CastManagerPigeonPigeonCodec.shared }
  /// Sets up an instance of `SessionManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SessionManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startSessionWithDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.startSessionWithDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSessionWithDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! StartSessionRequest
        do {
          let result = try api.startSessionWithDevice(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startSessionWithDeviceChannel.setMessageHandler(nil)
    }
    let endSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.endSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.endSession()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endSessionChannel.setMessageHandler(nil)
    }
    let endSessionAndStopCastingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.endSessionAndStopCasting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionAndStopCastingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.endSessionAndStopCasting()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endSessionAndStopCastingChannel.setMessageHandler(nil)
    }
    let setDeviceVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.setDeviceVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDeviceVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Double
        do {
          try api.setDeviceVolume(value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDeviceVolumeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SessionManagerFlutterApiProtocol {
  func onSessionChanged(session sessionArg: CastSessionPigeon?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SessionManagerFlutterApi: SessionManagerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CastManagerPigeonPigeonCodec {
    return CastManagerPigeonPigeonCodec.shared
  }
  func onSessionChanged(session sessionArg: CastSessionPigeon?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerFlutterApi.onSessionChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
