// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsGoogleCastContextPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsGoogleCastContextPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsGoogleCastContextPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashGoogleCastContextPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashGoogleCastContextPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashGoogleCastContextPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum DiscoveryCriteriaMethodPigeon: Int {
  case initWithApplicationID = 0
  case initWithNamespaces = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiscoveryCriteriaPigeon: Hashable {
  var method: DiscoveryCriteriaMethodPigeon
  var applicationID: String? = nil
  var namespaces: [String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiscoveryCriteriaPigeon? {
    let method = pigeonVar_list[0] as! DiscoveryCriteriaMethodPigeon
    let applicationID: String? = nilOrValue(pigeonVar_list[1])
    let namespaces: [String?]? = nilOrValue(pigeonVar_list[2])

    return DiscoveryCriteriaPigeon(
      method: method,
      applicationID: applicationID,
      namespaces: namespaces
    )
  }
  func toList() -> [Any?] {
    return [
      method,
      applicationID,
      namespaces,
    ]
  }
  static func == (lhs: DiscoveryCriteriaPigeon, rhs: DiscoveryCriteriaPigeon) -> Bool {
    return deepEqualsGoogleCastContextPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashGoogleCastContextPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastOptionsPigeon: Hashable {
  var physicalVolumeButtonsWillControlDeviceVolume: Bool
  var disableDiscoveryAutostart: Bool
  var disableAnalyticsLogging: Bool
  var suspendSessionsWhenBackgrounded: Bool
  var stopReceiverApplicationWhenEndingSession: Bool
  var startDiscoveryAfterFirstTapOnCastButton: Bool
  var stopCastingOnAppTerminated: Bool
  var appId: String? = nil
  var discoveryCriteria: DiscoveryCriteriaPigeon? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastOptionsPigeon? {
    let physicalVolumeButtonsWillControlDeviceVolume = pigeonVar_list[0] as! Bool
    let disableDiscoveryAutostart = pigeonVar_list[1] as! Bool
    let disableAnalyticsLogging = pigeonVar_list[2] as! Bool
    let suspendSessionsWhenBackgrounded = pigeonVar_list[3] as! Bool
    let stopReceiverApplicationWhenEndingSession = pigeonVar_list[4] as! Bool
    let startDiscoveryAfterFirstTapOnCastButton = pigeonVar_list[5] as! Bool
    let stopCastingOnAppTerminated = pigeonVar_list[6] as! Bool
    let appId: String? = nilOrValue(pigeonVar_list[7])
    let discoveryCriteria: DiscoveryCriteriaPigeon? = nilOrValue(pigeonVar_list[8])

    return CastOptionsPigeon(
      physicalVolumeButtonsWillControlDeviceVolume: physicalVolumeButtonsWillControlDeviceVolume,
      disableDiscoveryAutostart: disableDiscoveryAutostart,
      disableAnalyticsLogging: disableAnalyticsLogging,
      suspendSessionsWhenBackgrounded: suspendSessionsWhenBackgrounded,
      stopReceiverApplicationWhenEndingSession: stopReceiverApplicationWhenEndingSession,
      startDiscoveryAfterFirstTapOnCastButton: startDiscoveryAfterFirstTapOnCastButton,
      stopCastingOnAppTerminated: stopCastingOnAppTerminated,
      appId: appId,
      discoveryCriteria: discoveryCriteria
    )
  }
  func toList() -> [Any?] {
    return [
      physicalVolumeButtonsWillControlDeviceVolume,
      disableDiscoveryAutostart,
      disableAnalyticsLogging,
      suspendSessionsWhenBackgrounded,
      stopReceiverApplicationWhenEndingSession,
      startDiscoveryAfterFirstTapOnCastButton,
      stopCastingOnAppTerminated,
      appId,
      discoveryCriteria,
    ]
  }
  static func == (lhs: CastOptionsPigeon, rhs: CastOptionsPigeon) -> Bool {
    return deepEqualsGoogleCastContextPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashGoogleCastContextPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastContextInitRequest: Hashable {
  var options: CastOptionsPigeon


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastContextInitRequest? {
    let options = pigeonVar_list[0] as! CastOptionsPigeon

    return CastContextInitRequest(
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      options
    ]
  }
  static func == (lhs: CastContextInitRequest, rhs: CastContextInitRequest) -> Bool {
    return deepEqualsGoogleCastContextPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashGoogleCastContextPigeon(value: toList(), hasher: &hasher)
  }
}

private class GoogleCastContextPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DiscoveryCriteriaMethodPigeon(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DiscoveryCriteriaPigeon.fromList(self.readValue() as! [Any?])
    case 131:
      return CastOptionsPigeon.fromList(self.readValue() as! [Any?])
    case 132:
      return CastContextInitRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class GoogleCastContextPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DiscoveryCriteriaMethodPigeon {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DiscoveryCriteriaPigeon {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CastOptionsPigeon {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CastContextInitRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GoogleCastContextPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GoogleCastContextPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GoogleCastContextPigeonPigeonCodecWriter(data: data)
  }
}

class GoogleCastContextPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = GoogleCastContextPigeonPigeonCodec(readerWriter: GoogleCastContextPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GoogleCastContextHostApi {
  func setSharedInstanceWithOptions(request: CastContextInitRequest) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GoogleCastContextHostApiSetup {
  static var codec: FlutterStandardMessageCodec { GoogleCastContextPigeonPigeonCodec.shared }
  /// Sets up an instance of `GoogleCastContextHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GoogleCastContextHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setSharedInstanceWithOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.GoogleCastContextHostApi.setSharedInstanceWithOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSharedInstanceWithOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CastContextInitRequest
        do {
          let result = try api.setSharedInstanceWithOptions(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSharedInstanceWithOptionsChannel.setMessageHandler(nil)
    }
  }
}
