// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsRemoteMediaClientPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsRemoteMediaClientPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsRemoteMediaClientPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashRemoteMediaClientPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashRemoteMediaClientPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashRemoteMediaClientPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum RepeatModePigeon: Int {
  case off = 0
  case all = 1
  case single = 2
  case allAndShuffle = 3
}

enum MediaResumeStatePigeon: Int {
  case play = 0
  case pause = 1
  case unchanged = 2
}

/// Media track information
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaTrack: Hashable {
  var trackId: Int64
  var type: Int64
  var trackContentId: String
  var trackContentType: String
  var subtype: Int64
  var name: String
  var language: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaTrack? {
    let trackId = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! Int64
    let trackContentId = pigeonVar_list[2] as! String
    let trackContentType = pigeonVar_list[3] as! String
    let subtype = pigeonVar_list[4] as! Int64
    let name = pigeonVar_list[5] as! String
    let language = pigeonVar_list[6] as! String

    return MediaTrack(
      trackId: trackId,
      type: type,
      trackContentId: trackContentId,
      trackContentType: trackContentType,
      subtype: subtype,
      name: name,
      language: language
    )
  }
  func toList() -> [Any?] {
    return [
      trackId,
      type,
      trackContentId,
      trackContentType,
      subtype,
      name,
      language,
    ]
  }
  static func == (lhs: MediaTrack, rhs: MediaTrack) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Live seekable range for live media streams
///
/// Generated class from Pigeon that represents data sent in messages.
struct LiveSeekableRange: Hashable {
  var start: Int64
  var end: Int64
  var isMovingWindow: Bool
  var isLiveDone: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LiveSeekableRange? {
    let start = pigeonVar_list[0] as! Int64
    let end = pigeonVar_list[1] as! Int64
    let isMovingWindow = pigeonVar_list[2] as! Bool
    let isLiveDone = pigeonVar_list[3] as! Bool

    return LiveSeekableRange(
      start: start,
      end: end,
      isMovingWindow: isMovingWindow,
      isLiveDone: isLiveDone
    )
  }
  func toList() -> [Any?] {
    return [
      start,
      end,
      isMovingWindow,
      isLiveDone,
    ]
  }
  static func == (lhs: LiveSeekableRange, rhs: LiveSeekableRange) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Media information including content and track details
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfo: Hashable {
  var contentId: String
  var contentType: String
  var streamType: String
  var contentUrl: String
  var duration: Int64
  var customData: [String: Any?]? = nil
  var tracks: [MediaTrack?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfo? {
    let contentId = pigeonVar_list[0] as! String
    let contentType = pigeonVar_list[1] as! String
    let streamType = pigeonVar_list[2] as! String
    let contentUrl = pigeonVar_list[3] as! String
    let duration = pigeonVar_list[4] as! Int64
    let customData: [String: Any?]? = nilOrValue(pigeonVar_list[5])
    let tracks: [MediaTrack?]? = nilOrValue(pigeonVar_list[6])

    return MediaInfo(
      contentId: contentId,
      contentType: contentType,
      streamType: streamType,
      contentUrl: contentUrl,
      duration: duration,
      customData: customData,
      tracks: tracks
    )
  }
  func toList() -> [Any?] {
    return [
      contentId,
      contentType,
      streamType,
      contentUrl,
      duration,
      customData,
      tracks,
    ]
  }
  static func == (lhs: MediaInfo, rhs: MediaInfo) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Volume information
///
/// Generated class from Pigeon that represents data sent in messages.
struct Volume: Hashable {
  var level: Double
  var muted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Volume? {
    let level = pigeonVar_list[0] as! Double
    let muted = pigeonVar_list[1] as! Bool

    return Volume(
      level: level,
      muted: muted
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      muted,
    ]
  }
  static func == (lhs: Volume, rhs: Volume) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Media queue item
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaQueueItem: Hashable {
  var itemId: Int64
  var preLoadTime: Int64
  var startTime: Int64
  var playbackDuration: Int64
  var media: MediaInfo? = nil
  var autoplay: Bool
  var activeTrackIds: [Int64?]? = nil
  var customData: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaQueueItem? {
    let itemId = pigeonVar_list[0] as! Int64
    let preLoadTime = pigeonVar_list[1] as! Int64
    let startTime = pigeonVar_list[2] as! Int64
    let playbackDuration = pigeonVar_list[3] as! Int64
    let media: MediaInfo? = nilOrValue(pigeonVar_list[4])
    let autoplay = pigeonVar_list[5] as! Bool
    let activeTrackIds: [Int64?]? = nilOrValue(pigeonVar_list[6])
    let customData: [String: Any?]? = nilOrValue(pigeonVar_list[7])

    return MediaQueueItem(
      itemId: itemId,
      preLoadTime: preLoadTime,
      startTime: startTime,
      playbackDuration: playbackDuration,
      media: media,
      autoplay: autoplay,
      activeTrackIds: activeTrackIds,
      customData: customData
    )
  }
  func toList() -> [Any?] {
    return [
      itemId,
      preLoadTime,
      startTime,
      playbackDuration,
      media,
      autoplay,
      activeTrackIds,
      customData,
    ]
  }
  static func == (lhs: MediaQueueItem, rhs: MediaQueueItem) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Complete media status
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaStatus: Hashable {
  var mediaSessionId: Int64
  var playerState: String
  var idleReason: String
  var playbackRate: Double
  var media: MediaInfo? = nil
  var volume: Volume
  var repeatMode: String
  var currentItemId: Int64
  var activeTrackIds: [Int64?]? = nil
  var liveSeekableRange: LiveSeekableRange? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaStatus? {
    let mediaSessionId = pigeonVar_list[0] as! Int64
    let playerState = pigeonVar_list[1] as! String
    let idleReason = pigeonVar_list[2] as! String
    let playbackRate = pigeonVar_list[3] as! Double
    let media: MediaInfo? = nilOrValue(pigeonVar_list[4])
    let volume = pigeonVar_list[5] as! Volume
    let repeatMode = pigeonVar_list[6] as! String
    let currentItemId = pigeonVar_list[7] as! Int64
    let activeTrackIds: [Int64?]? = nilOrValue(pigeonVar_list[8])
    let liveSeekableRange: LiveSeekableRange? = nilOrValue(pigeonVar_list[9])

    return MediaStatus(
      mediaSessionId: mediaSessionId,
      playerState: playerState,
      idleReason: idleReason,
      playbackRate: playbackRate,
      media: media,
      volume: volume,
      repeatMode: repeatMode,
      currentItemId: currentItemId,
      activeTrackIds: activeTrackIds,
      liveSeekableRange: liveSeekableRange
    )
  }
  func toList() -> [Any?] {
    return [
      mediaSessionId,
      playerState,
      idleReason,
      playbackRate,
      media,
      volume,
      repeatMode,
      currentItemId,
      activeTrackIds,
      liveSeekableRange,
    ]
  }
  static func == (lhs: MediaStatus, rhs: MediaStatus) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QueueLoadOptionsPigeon: Hashable {
  var startIndex: Int64
  var playPosition: Int64
  var repeatMode: RepeatModePigeon
  var customData: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueLoadOptionsPigeon? {
    let startIndex = pigeonVar_list[0] as! Int64
    let playPosition = pigeonVar_list[1] as! Int64
    let repeatMode = pigeonVar_list[2] as! RepeatModePigeon
    let customData: [String: Any?]? = nilOrValue(pigeonVar_list[3])

    return QueueLoadOptionsPigeon(
      startIndex: startIndex,
      playPosition: playPosition,
      repeatMode: repeatMode,
      customData: customData
    )
  }
  func toList() -> [Any?] {
    return [
      startIndex,
      playPosition,
      repeatMode,
      customData,
    ]
  }
  static func == (lhs: QueueLoadOptionsPigeon, rhs: QueueLoadOptionsPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SeekOptionPigeon: Hashable {
  var position: Int64
  var relative: Bool
  var resumeState: MediaResumeStatePigeon
  var seekToInfinity: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SeekOptionPigeon? {
    let position = pigeonVar_list[0] as! Int64
    let relative = pigeonVar_list[1] as! Bool
    let resumeState = pigeonVar_list[2] as! MediaResumeStatePigeon
    let seekToInfinity = pigeonVar_list[3] as! Bool

    return SeekOptionPigeon(
      position: position,
      relative: relative,
      resumeState: resumeState,
      seekToInfinity: seekToInfinity
    )
  }
  func toList() -> [Any?] {
    return [
      position,
      relative,
      resumeState,
      seekToInfinity,
    ]
  }
  static func == (lhs: SeekOptionPigeon, rhs: SeekOptionPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LoadMediaRequestPigeon: Hashable {
  var mediaInfo: MediaInfo
  var autoPlay: Bool
  var playPosition: Int64
  var playbackRate: Double
  var activeTrackIds: [Int64?]? = nil
  var credentials: String? = nil
  var credentialsType: String? = nil
  var customData: [String: Any?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LoadMediaRequestPigeon? {
    let mediaInfo = pigeonVar_list[0] as! MediaInfo
    let autoPlay = pigeonVar_list[1] as! Bool
    let playPosition = pigeonVar_list[2] as! Int64
    let playbackRate = pigeonVar_list[3] as! Double
    let activeTrackIds: [Int64?]? = nilOrValue(pigeonVar_list[4])
    let credentials: String? = nilOrValue(pigeonVar_list[5])
    let credentialsType: String? = nilOrValue(pigeonVar_list[6])
    let customData: [String: Any?]? = nilOrValue(pigeonVar_list[7])

    return LoadMediaRequestPigeon(
      mediaInfo: mediaInfo,
      autoPlay: autoPlay,
      playPosition: playPosition,
      playbackRate: playbackRate,
      activeTrackIds: activeTrackIds,
      credentials: credentials,
      credentialsType: credentialsType,
      customData: customData
    )
  }
  func toList() -> [Any?] {
    return [
      mediaInfo,
      autoPlay,
      playPosition,
      playbackRate,
      activeTrackIds,
      credentials,
      credentialsType,
      customData,
    ]
  }
  static func == (lhs: LoadMediaRequestPigeon, rhs: LoadMediaRequestPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QueueLoadRequestPigeon: Hashable {
  var items: [MediaQueueItem?]
  var options: QueueLoadOptionsPigeon? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueLoadRequestPigeon? {
    let items = pigeonVar_list[0] as! [MediaQueueItem?]
    let options: QueueLoadOptionsPigeon? = nilOrValue(pigeonVar_list[1])

    return QueueLoadRequestPigeon(
      items: items,
      options: options
    )
  }
  func toList() -> [Any?] {
    return [
      items,
      options,
    ]
  }
  static func == (lhs: QueueLoadRequestPigeon, rhs: QueueLoadRequestPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QueueInsertItemsRequestPigeon: Hashable {
  var items: [MediaQueueItem?]
  var beforeItemWithId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueInsertItemsRequestPigeon? {
    let items = pigeonVar_list[0] as! [MediaQueueItem?]
    let beforeItemWithId: Int64? = nilOrValue(pigeonVar_list[1])

    return QueueInsertItemsRequestPigeon(
      items: items,
      beforeItemWithId: beforeItemWithId
    )
  }
  func toList() -> [Any?] {
    return [
      items,
      beforeItemWithId,
    ]
  }
  static func == (lhs: QueueInsertItemsRequestPigeon, rhs: QueueInsertItemsRequestPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QueueInsertItemAndPlayRequestPigeon: Hashable {
  var item: MediaQueueItem
  var beforeItemWithId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueInsertItemAndPlayRequestPigeon? {
    let item = pigeonVar_list[0] as! MediaQueueItem
    let beforeItemWithId = pigeonVar_list[1] as! Int64

    return QueueInsertItemAndPlayRequestPigeon(
      item: item,
      beforeItemWithId: beforeItemWithId
    )
  }
  func toList() -> [Any?] {
    return [
      item,
      beforeItemWithId,
    ]
  }
  static func == (lhs: QueueInsertItemAndPlayRequestPigeon, rhs: QueueInsertItemAndPlayRequestPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct QueueReorderItemsRequestPigeon: Hashable {
  var itemsIds: [Int64?]
  var beforeItemWithId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueReorderItemsRequestPigeon? {
    let itemsIds = pigeonVar_list[0] as! [Int64?]
    let beforeItemWithId: Int64? = nilOrValue(pigeonVar_list[1])

    return QueueReorderItemsRequestPigeon(
      itemsIds: itemsIds,
      beforeItemWithId: beforeItemWithId
    )
  }
  func toList() -> [Any?] {
    return [
      itemsIds,
      beforeItemWithId,
    ]
  }
  static func == (lhs: QueueReorderItemsRequestPigeon, rhs: QueueReorderItemsRequestPigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Player position update
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlayerPositionUpdate: Hashable {
  var progress: Int64
  var duration: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlayerPositionUpdate? {
    let progress = pigeonVar_list[0] as! Int64
    let duration = pigeonVar_list[1] as! Int64

    return PlayerPositionUpdate(
      progress: progress,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      progress,
      duration,
    ]
  }
  static func == (lhs: PlayerPositionUpdate, rhs: PlayerPositionUpdate) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TextTrackStylePigeon: Hashable {
  var backgroundColor: String? = nil
  var customData: [String: Any?]? = nil
  var edgeColor: String? = nil
  var fontFamily: String? = nil
  var fontGenericFamily: String? = nil
  var fontScale: Int64? = nil
  var fontStyle: String? = nil
  var foregroundColor: String? = nil
  var windowColor: String? = nil
  var windowRoundedCornerRadius: Double? = nil
  var windowType: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TextTrackStylePigeon? {
    let backgroundColor: String? = nilOrValue(pigeonVar_list[0])
    let customData: [String: Any?]? = nilOrValue(pigeonVar_list[1])
    let edgeColor: String? = nilOrValue(pigeonVar_list[2])
    let fontFamily: String? = nilOrValue(pigeonVar_list[3])
    let fontGenericFamily: String? = nilOrValue(pigeonVar_list[4])
    let fontScale: Int64? = nilOrValue(pigeonVar_list[5])
    let fontStyle: String? = nilOrValue(pigeonVar_list[6])
    let foregroundColor: String? = nilOrValue(pigeonVar_list[7])
    let windowColor: String? = nilOrValue(pigeonVar_list[8])
    let windowRoundedCornerRadius: Double? = nilOrValue(pigeonVar_list[9])
    let windowType: String? = nilOrValue(pigeonVar_list[10])

    return TextTrackStylePigeon(
      backgroundColor: backgroundColor,
      customData: customData,
      edgeColor: edgeColor,
      fontFamily: fontFamily,
      fontGenericFamily: fontGenericFamily,
      fontScale: fontScale,
      fontStyle: fontStyle,
      foregroundColor: foregroundColor,
      windowColor: windowColor,
      windowRoundedCornerRadius: windowRoundedCornerRadius,
      windowType: windowType
    )
  }
  func toList() -> [Any?] {
    return [
      backgroundColor,
      customData,
      edgeColor,
      fontFamily,
      fontGenericFamily,
      fontScale,
      fontStyle,
      foregroundColor,
      windowColor,
      windowRoundedCornerRadius,
      windowType,
    ]
  }
  static func == (lhs: TextTrackStylePigeon, rhs: TextTrackStylePigeon) -> Bool {
    return deepEqualsRemoteMediaClientPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashRemoteMediaClientPigeon(value: toList(), hasher: &hasher)
  }
}

private class RemoteMediaClientPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RepeatModePigeon(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MediaResumeStatePigeon(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MediaTrack.fromList(self.readValue() as! [Any?])
    case 132:
      return LiveSeekableRange.fromList(self.readValue() as! [Any?])
    case 133:
      return MediaInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return Volume.fromList(self.readValue() as! [Any?])
    case 135:
      return MediaQueueItem.fromList(self.readValue() as! [Any?])
    case 136:
      return MediaStatus.fromList(self.readValue() as! [Any?])
    case 137:
      return QueueLoadOptionsPigeon.fromList(self.readValue() as! [Any?])
    case 138:
      return SeekOptionPigeon.fromList(self.readValue() as! [Any?])
    case 139:
      return LoadMediaRequestPigeon.fromList(self.readValue() as! [Any?])
    case 140:
      return QueueLoadRequestPigeon.fromList(self.readValue() as! [Any?])
    case 141:
      return QueueInsertItemsRequestPigeon.fromList(self.readValue() as! [Any?])
    case 142:
      return QueueInsertItemAndPlayRequestPigeon.fromList(self.readValue() as! [Any?])
    case 143:
      return QueueReorderItemsRequestPigeon.fromList(self.readValue() as! [Any?])
    case 144:
      return PlayerPositionUpdate.fromList(self.readValue() as! [Any?])
    case 145:
      return TextTrackStylePigeon.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class RemoteMediaClientPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RepeatModePigeon {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaResumeStatePigeon {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaTrack {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? LiveSeekableRange {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? Volume {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? MediaQueueItem {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? MediaStatus {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? QueueLoadOptionsPigeon {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? SeekOptionPigeon {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? LoadMediaRequestPigeon {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? QueueLoadRequestPigeon {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? QueueInsertItemsRequestPigeon {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? QueueInsertItemAndPlayRequestPigeon {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? QueueReorderItemsRequestPigeon {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PlayerPositionUpdate {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? TextTrackStylePigeon {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class RemoteMediaClientPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return RemoteMediaClientPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return RemoteMediaClientPigeonPigeonCodecWriter(data: data)
  }
}

class RemoteMediaClientPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = RemoteMediaClientPigeonPigeonCodec(readerWriter: RemoteMediaClientPigeonPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RemoteMediaClientHostApi {
  func loadMedia(request: LoadMediaRequestPigeon) throws
  func queueLoadItems(request: QueueLoadRequestPigeon) throws
  func queueInsertItems(request: QueueInsertItemsRequestPigeon) throws
  func queueInsertItemAndPlay(request: QueueInsertItemAndPlayRequestPigeon) throws
  func queueNextItem() throws
  func queuePrevItem() throws
  func queueJumpToItemWithId(itemId: Int64) throws
  func queueRemoveItemsWithIds(itemIds: [Int64?]) throws
  func queueReorderItems(request: QueueReorderItemsRequestPigeon) throws
  func seek(request: SeekOptionPigeon) throws
  func setActiveTrackIds(trackIds: [Int64?]) throws
  func setPlaybackRate(rate: Double) throws
  func setTextTrackStyle(textTrackStyle: TextTrackStylePigeon) throws
  func play() throws
  func pause() throws
  func stop() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RemoteMediaClientHostApiSetup {
  static var codec: FlutterStandardMessageCodec { RemoteMediaClientPigeonPigeonCodec.shared }
  /// Sets up an instance of `RemoteMediaClientHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RemoteMediaClientHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.loadMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! LoadMediaRequestPigeon
        do {
          try api.loadMedia(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadMediaChannel.setMessageHandler(nil)
    }
    let queueLoadItemsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueLoadItems\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueLoadItemsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! QueueLoadRequestPigeon
        do {
          try api.queueLoadItems(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueLoadItemsChannel.setMessageHandler(nil)
    }
    let queueInsertItemsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueInsertItems\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueInsertItemsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! QueueInsertItemsRequestPigeon
        do {
          try api.queueInsertItems(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueInsertItemsChannel.setMessageHandler(nil)
    }
    let queueInsertItemAndPlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueInsertItemAndPlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueInsertItemAndPlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! QueueInsertItemAndPlayRequestPigeon
        do {
          try api.queueInsertItemAndPlay(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueInsertItemAndPlayChannel.setMessageHandler(nil)
    }
    let queueNextItemChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueNextItem\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueNextItemChannel.setMessageHandler { _, reply in
        do {
          try api.queueNextItem()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueNextItemChannel.setMessageHandler(nil)
    }
    let queuePrevItemChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queuePrevItem\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queuePrevItemChannel.setMessageHandler { _, reply in
        do {
          try api.queuePrevItem()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queuePrevItemChannel.setMessageHandler(nil)
    }
    let queueJumpToItemWithIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueJumpToItemWithId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueJumpToItemWithIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdArg = args[0] as! Int64
        do {
          try api.queueJumpToItemWithId(itemId: itemIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueJumpToItemWithIdChannel.setMessageHandler(nil)
    }
    let queueRemoveItemsWithIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueRemoveItemsWithIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueRemoveItemsWithIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let itemIdsArg = args[0] as! [Int64?]
        do {
          try api.queueRemoveItemsWithIds(itemIds: itemIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueRemoveItemsWithIdsChannel.setMessageHandler(nil)
    }
    let queueReorderItemsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueReorderItems\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queueReorderItemsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! QueueReorderItemsRequestPigeon
        do {
          try api.queueReorderItems(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queueReorderItemsChannel.setMessageHandler(nil)
    }
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SeekOptionPigeon
        do {
          try api.seek(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    let setActiveTrackIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setActiveTrackIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setActiveTrackIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let trackIdsArg = args[0] as! [Int64?]
        do {
          try api.setActiveTrackIds(trackIds: trackIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setActiveTrackIdsChannel.setMessageHandler(nil)
    }
    let setPlaybackRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setPlaybackRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPlaybackRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rateArg = args[0] as! Double
        do {
          try api.setPlaybackRate(rate: rateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPlaybackRateChannel.setMessageHandler(nil)
    }
    let setTextTrackStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setTextTrackStyle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTextTrackStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textTrackStyleArg = args[0] as! TextTrackStylePigeon
        do {
          try api.setTextTrackStyle(textTrackStyle: textTrackStyleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTextTrackStyleChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol RemoteMediaClientFlutterApiProtocol {
  func onMediaStatusChanged(status statusArg: MediaStatus?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onQueueStatusChanged(queueItems queueItemsArg: [MediaQueueItem?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPlayerPositionChanged(update updateArg: PlayerPositionUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class RemoteMediaClientFlutterApi: RemoteMediaClientFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: RemoteMediaClientPigeonPigeonCodec {
    return RemoteMediaClientPigeonPigeonCodec.shared
  }
  func onMediaStatusChanged(status statusArg: MediaStatus?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onMediaStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onQueueStatusChanged(queueItems queueItemsArg: [MediaQueueItem?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onQueueStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([queueItemsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPlayerPositionChanged(update updateArg: PlayerPositionUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onPlayerPositionChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
