// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.felnanuke.google_cast.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CastManagerPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ConnectionStatePigeon(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3);

  companion object {
    fun ofRaw(raw: Int): ConnectionStatePigeon? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CastDevicePigeon (
  val deviceId: String,
  val friendlyName: String,
  val modelName: String? = null,
  val statusText: String? = null,
  val deviceVersion: String,
  val isOnLocalNetwork: Boolean,
  val category: String,
  val uniqueId: String,
  val index: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CastDevicePigeon {
      val deviceId = pigeonVar_list[0] as String
      val friendlyName = pigeonVar_list[1] as String
      val modelName = pigeonVar_list[2] as String?
      val statusText = pigeonVar_list[3] as String?
      val deviceVersion = pigeonVar_list[4] as String
      val isOnLocalNetwork = pigeonVar_list[5] as Boolean
      val category = pigeonVar_list[6] as String
      val uniqueId = pigeonVar_list[7] as String
      val index = pigeonVar_list[8] as Long?
      return CastDevicePigeon(deviceId, friendlyName, modelName, statusText, deviceVersion, isOnLocalNetwork, category, uniqueId, index)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      friendlyName,
      modelName,
      statusText,
      deviceVersion,
      isOnLocalNetwork,
      category,
      uniqueId,
      index,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CastDevicePigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return CastManagerPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CastSessionPigeon (
  val device: CastDevicePigeon? = null,
  val sessionId: String? = null,
  val connectionState: ConnectionStatePigeon,
  val currentDeviceMuted: Boolean,
  val currentDeviceVolume: Double,
  val deviceStatusText: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CastSessionPigeon {
      val device = pigeonVar_list[0] as CastDevicePigeon?
      val sessionId = pigeonVar_list[1] as String?
      val connectionState = pigeonVar_list[2] as ConnectionStatePigeon
      val currentDeviceMuted = pigeonVar_list[3] as Boolean
      val currentDeviceVolume = pigeonVar_list[4] as Double
      val deviceStatusText = pigeonVar_list[5] as String
      return CastSessionPigeon(device, sessionId, connectionState, currentDeviceMuted, currentDeviceVolume, deviceStatusText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      device,
      sessionId,
      connectionState,
      currentDeviceMuted,
      currentDeviceVolume,
      deviceStatusText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CastSessionPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return CastManagerPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StartSessionRequest (
  val deviceId: String? = null,
  val deviceIndex: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartSessionRequest {
      val deviceId = pigeonVar_list[0] as String?
      val deviceIndex = pigeonVar_list[1] as Long?
      return StartSessionRequest(deviceId, deviceIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      deviceId,
      deviceIndex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StartSessionRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return CastManagerPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CastManagerPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionStatePigeon.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CastDevicePigeon.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CastSessionPigeon.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartSessionRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnectionStatePigeon -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is CastDevicePigeon -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CastSessionPigeon -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is StartSessionRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DiscoveryManagerHostApi {
  fun startDiscovery()
  fun stopDiscovery()
  fun isDiscoveryActiveForDeviceCategory(deviceCategory: String): Boolean

  companion object {
    /** The codec used by DiscoveryManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastManagerPigeonPigeonCodec()
    }
    /** Sets up an instance of `DiscoveryManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DiscoveryManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerHostApi.startDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerHostApi.stopDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerHostApi.isDiscoveryActiveForDeviceCategory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceCategoryArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.isDiscoveryActiveForDeviceCategory(deviceCategoryArg))
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DiscoveryManagerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DiscoveryManagerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastManagerPigeonPigeonCodec()
    }
  }
  fun onDevicesChanged(devicesArg: List<CastDevicePigeon>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.DiscoveryManagerFlutterApi.onDevicesChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(devicesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CastManagerPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SessionManagerHostApi {
  fun startSessionWithDevice(request: StartSessionRequest): Boolean
  fun endSession(): Boolean
  fun endSessionAndStopCasting(): Boolean
  fun setDeviceVolume(value: Double)

  companion object {
    /** The codec used by SessionManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastManagerPigeonPigeonCodec()
    }
    /** Sets up an instance of `SessionManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SessionManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.startSessionWithDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as StartSessionRequest
            val wrapped: List<Any?> = try {
              listOf(api.startSessionWithDevice(requestArg))
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.endSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.endSession())
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.endSessionAndStopCasting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.endSessionAndStopCasting())
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerHostApi.setDeviceVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setDeviceVolume(valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              CastManagerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SessionManagerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SessionManagerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastManagerPigeonPigeonCodec()
    }
  }
  fun onSessionChanged(sessionArg: CastSessionPigeon?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.SessionManagerFlutterApi.onSessionChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CastManagerPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
