// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.felnanuke.google_cast.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object GoogleCastContextPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

enum class DiscoveryCriteriaMethodPigeon(val raw: Int) {
  INIT_WITH_APPLICATION_ID(0),
  INIT_WITH_NAMESPACES(1);

  companion object {
    fun ofRaw(raw: Int): DiscoveryCriteriaMethodPigeon? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiscoveryCriteriaPigeon (
  val method: DiscoveryCriteriaMethodPigeon,
  val applicationID: String? = null,
  val namespaces: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiscoveryCriteriaPigeon {
      val method = pigeonVar_list[0] as DiscoveryCriteriaMethodPigeon
      val applicationID = pigeonVar_list[1] as String?
      val namespaces = pigeonVar_list[2] as List<String?>?
      return DiscoveryCriteriaPigeon(method, applicationID, namespaces)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      method,
      applicationID,
      namespaces,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DiscoveryCriteriaPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return GoogleCastContextPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CastOptionsPigeon (
  val physicalVolumeButtonsWillControlDeviceVolume: Boolean,
  val disableDiscoveryAutostart: Boolean,
  val disableAnalyticsLogging: Boolean,
  val suspendSessionsWhenBackgrounded: Boolean,
  val stopReceiverApplicationWhenEndingSession: Boolean,
  val startDiscoveryAfterFirstTapOnCastButton: Boolean,
  val stopCastingOnAppTerminated: Boolean,
  val appId: String? = null,
  val discoveryCriteria: DiscoveryCriteriaPigeon? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CastOptionsPigeon {
      val physicalVolumeButtonsWillControlDeviceVolume = pigeonVar_list[0] as Boolean
      val disableDiscoveryAutostart = pigeonVar_list[1] as Boolean
      val disableAnalyticsLogging = pigeonVar_list[2] as Boolean
      val suspendSessionsWhenBackgrounded = pigeonVar_list[3] as Boolean
      val stopReceiverApplicationWhenEndingSession = pigeonVar_list[4] as Boolean
      val startDiscoveryAfterFirstTapOnCastButton = pigeonVar_list[5] as Boolean
      val stopCastingOnAppTerminated = pigeonVar_list[6] as Boolean
      val appId = pigeonVar_list[7] as String?
      val discoveryCriteria = pigeonVar_list[8] as DiscoveryCriteriaPigeon?
      return CastOptionsPigeon(physicalVolumeButtonsWillControlDeviceVolume, disableDiscoveryAutostart, disableAnalyticsLogging, suspendSessionsWhenBackgrounded, stopReceiverApplicationWhenEndingSession, startDiscoveryAfterFirstTapOnCastButton, stopCastingOnAppTerminated, appId, discoveryCriteria)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      physicalVolumeButtonsWillControlDeviceVolume,
      disableDiscoveryAutostart,
      disableAnalyticsLogging,
      suspendSessionsWhenBackgrounded,
      stopReceiverApplicationWhenEndingSession,
      startDiscoveryAfterFirstTapOnCastButton,
      stopCastingOnAppTerminated,
      appId,
      discoveryCriteria,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CastOptionsPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return GoogleCastContextPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CastContextInitRequest (
  val options: CastOptionsPigeon
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CastContextInitRequest {
      val options = pigeonVar_list[0] as CastOptionsPigeon
      return CastContextInitRequest(options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CastContextInitRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return GoogleCastContextPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class GoogleCastContextPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DiscoveryCriteriaMethodPigeon.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiscoveryCriteriaPigeon.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CastOptionsPigeon.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CastContextInitRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DiscoveryCriteriaMethodPigeon -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is DiscoveryCriteriaPigeon -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CastOptionsPigeon -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CastContextInitRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GoogleCastContextHostApi {
  fun setSharedInstanceWithOptions(request: CastContextInitRequest): Boolean

  companion object {
    /** The codec used by GoogleCastContextHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      GoogleCastContextPigeonPigeonCodec()
    }
    /** Sets up an instance of `GoogleCastContextHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GoogleCastContextHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.GoogleCastContextHostApi.setSharedInstanceWithOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CastContextInitRequest
            val wrapped: List<Any?> = try {
              listOf(api.setSharedInstanceWithOptions(requestArg))
            } catch (exception: Throwable) {
              GoogleCastContextPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
