// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.felnanuke.google_cast.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RemoteMediaClientPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

enum class RepeatModePigeon(val raw: Int) {
  OFF(0),
  ALL(1),
  SINGLE(2),
  ALL_AND_SHUFFLE(3);

  companion object {
    fun ofRaw(raw: Int): RepeatModePigeon? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaResumeStatePigeon(val raw: Int) {
  PLAY(0),
  PAUSE(1),
  UNCHANGED(2);

  companion object {
    fun ofRaw(raw: Int): MediaResumeStatePigeon? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Media track information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaTrack (
  val trackId: Long,
  val type: Long,
  val trackContentId: String,
  val trackContentType: String,
  val subtype: Long,
  val name: String,
  val language: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaTrack {
      val trackId = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as Long
      val trackContentId = pigeonVar_list[2] as String
      val trackContentType = pigeonVar_list[3] as String
      val subtype = pigeonVar_list[4] as Long
      val name = pigeonVar_list[5] as String
      val language = pigeonVar_list[6] as String
      return MediaTrack(trackId, type, trackContentId, trackContentType, subtype, name, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      trackId,
      type,
      trackContentId,
      trackContentType,
      subtype,
      name,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaTrack) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Live seekable range for live media streams
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LiveSeekableRange (
  val start: Long,
  val end: Long,
  val isMovingWindow: Boolean,
  val isLiveDone: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LiveSeekableRange {
      val start = pigeonVar_list[0] as Long
      val end = pigeonVar_list[1] as Long
      val isMovingWindow = pigeonVar_list[2] as Boolean
      val isLiveDone = pigeonVar_list[3] as Boolean
      return LiveSeekableRange(start, end, isMovingWindow, isLiveDone)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      start,
      end,
      isMovingWindow,
      isLiveDone,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LiveSeekableRange) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Media information including content and track details
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaInfo (
  val contentId: String,
  val contentType: String,
  val streamType: String,
  val contentUrl: String,
  val duration: Long,
  val customData: Map<String, Any?>? = null,
  val tracks: List<MediaTrack?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfo {
      val contentId = pigeonVar_list[0] as String
      val contentType = pigeonVar_list[1] as String
      val streamType = pigeonVar_list[2] as String
      val contentUrl = pigeonVar_list[3] as String
      val duration = pigeonVar_list[4] as Long
      val customData = pigeonVar_list[5] as Map<String, Any?>?
      val tracks = pigeonVar_list[6] as List<MediaTrack?>?
      return MediaInfo(contentId, contentType, streamType, contentUrl, duration, customData, tracks)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentId,
      contentType,
      streamType,
      contentUrl,
      duration,
      customData,
      tracks,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Volume information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Volume (
  val level: Double,
  val muted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Volume {
      val level = pigeonVar_list[0] as Double
      val muted = pigeonVar_list[1] as Boolean
      return Volume(level, muted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      muted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Volume) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Media queue item
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaQueueItem (
  val itemId: Long,
  val preLoadTime: Long,
  val startTime: Long,
  val playbackDuration: Long,
  val media: MediaInfo? = null,
  val autoplay: Boolean,
  val activeTrackIds: List<Long?>? = null,
  val customData: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaQueueItem {
      val itemId = pigeonVar_list[0] as Long
      val preLoadTime = pigeonVar_list[1] as Long
      val startTime = pigeonVar_list[2] as Long
      val playbackDuration = pigeonVar_list[3] as Long
      val media = pigeonVar_list[4] as MediaInfo?
      val autoplay = pigeonVar_list[5] as Boolean
      val activeTrackIds = pigeonVar_list[6] as List<Long?>?
      val customData = pigeonVar_list[7] as Map<String, Any?>?
      return MediaQueueItem(itemId, preLoadTime, startTime, playbackDuration, media, autoplay, activeTrackIds, customData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      itemId,
      preLoadTime,
      startTime,
      playbackDuration,
      media,
      autoplay,
      activeTrackIds,
      customData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaQueueItem) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Complete media status
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaStatus (
  val mediaSessionId: Long,
  val playerState: String,
  val idleReason: String,
  val playbackRate: Double,
  val media: MediaInfo? = null,
  val volume: Volume,
  val repeatMode: String,
  val currentItemId: Long,
  val activeTrackIds: List<Long?>? = null,
  val liveSeekableRange: LiveSeekableRange? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaStatus {
      val mediaSessionId = pigeonVar_list[0] as Long
      val playerState = pigeonVar_list[1] as String
      val idleReason = pigeonVar_list[2] as String
      val playbackRate = pigeonVar_list[3] as Double
      val media = pigeonVar_list[4] as MediaInfo?
      val volume = pigeonVar_list[5] as Volume
      val repeatMode = pigeonVar_list[6] as String
      val currentItemId = pigeonVar_list[7] as Long
      val activeTrackIds = pigeonVar_list[8] as List<Long?>?
      val liveSeekableRange = pigeonVar_list[9] as LiveSeekableRange?
      return MediaStatus(mediaSessionId, playerState, idleReason, playbackRate, media, volume, repeatMode, currentItemId, activeTrackIds, liveSeekableRange)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaSessionId,
      playerState,
      idleReason,
      playbackRate,
      media,
      volume,
      repeatMode,
      currentItemId,
      activeTrackIds,
      liveSeekableRange,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaStatus) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QueueLoadOptionsPigeon (
  val startIndex: Long,
  val playPosition: Long,
  val repeatMode: RepeatModePigeon,
  val customData: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueueLoadOptionsPigeon {
      val startIndex = pigeonVar_list[0] as Long
      val playPosition = pigeonVar_list[1] as Long
      val repeatMode = pigeonVar_list[2] as RepeatModePigeon
      val customData = pigeonVar_list[3] as Map<String, Any?>?
      return QueueLoadOptionsPigeon(startIndex, playPosition, repeatMode, customData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startIndex,
      playPosition,
      repeatMode,
      customData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is QueueLoadOptionsPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SeekOptionPigeon (
  val position: Long,
  val relative: Boolean,
  val resumeState: MediaResumeStatePigeon,
  val seekToInfinity: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SeekOptionPigeon {
      val position = pigeonVar_list[0] as Long
      val relative = pigeonVar_list[1] as Boolean
      val resumeState = pigeonVar_list[2] as MediaResumeStatePigeon
      val seekToInfinity = pigeonVar_list[3] as Boolean
      return SeekOptionPigeon(position, relative, resumeState, seekToInfinity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      position,
      relative,
      resumeState,
      seekToInfinity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SeekOptionPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetPlaybackRateRequestPigeon (
  val rate: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetPlaybackRateRequestPigeon {
      val rate = pigeonVar_list[0] as Double
      return SetPlaybackRateRequestPigeon(rate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetPlaybackRateRequestPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoadMediaRequestPigeon (
  val mediaInfo: MediaInfo,
  val autoPlay: Boolean,
  val playPosition: Long,
  val playbackRate: Double,
  val activeTrackIds: List<Long?>? = null,
  val credentials: String? = null,
  val credentialsType: String? = null,
  val customData: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoadMediaRequestPigeon {
      val mediaInfo = pigeonVar_list[0] as MediaInfo
      val autoPlay = pigeonVar_list[1] as Boolean
      val playPosition = pigeonVar_list[2] as Long
      val playbackRate = pigeonVar_list[3] as Double
      val activeTrackIds = pigeonVar_list[4] as List<Long?>?
      val credentials = pigeonVar_list[5] as String?
      val credentialsType = pigeonVar_list[6] as String?
      val customData = pigeonVar_list[7] as Map<String, Any?>?
      return LoadMediaRequestPigeon(mediaInfo, autoPlay, playPosition, playbackRate, activeTrackIds, credentials, credentialsType, customData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaInfo,
      autoPlay,
      playPosition,
      playbackRate,
      activeTrackIds,
      credentials,
      credentialsType,
      customData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LoadMediaRequestPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QueueLoadRequestPigeon (
  val items: List<MediaQueueItem?>,
  val options: QueueLoadOptionsPigeon? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueueLoadRequestPigeon {
      val items = pigeonVar_list[0] as List<MediaQueueItem?>
      val options = pigeonVar_list[1] as QueueLoadOptionsPigeon?
      return QueueLoadRequestPigeon(items, options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is QueueLoadRequestPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QueueInsertItemsRequestPigeon (
  val items: List<MediaQueueItem?>,
  val beforeItemWithId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueueInsertItemsRequestPigeon {
      val items = pigeonVar_list[0] as List<MediaQueueItem?>
      val beforeItemWithId = pigeonVar_list[1] as Long?
      return QueueInsertItemsRequestPigeon(items, beforeItemWithId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      beforeItemWithId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is QueueInsertItemsRequestPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QueueInsertItemAndPlayRequestPigeon (
  val item: MediaQueueItem,
  val beforeItemWithId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueueInsertItemAndPlayRequestPigeon {
      val item = pigeonVar_list[0] as MediaQueueItem
      val beforeItemWithId = pigeonVar_list[1] as Long
      return QueueInsertItemAndPlayRequestPigeon(item, beforeItemWithId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      item,
      beforeItemWithId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is QueueInsertItemAndPlayRequestPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QueueReorderItemsRequestPigeon (
  val itemsIds: List<Long?>,
  val beforeItemWithId: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueueReorderItemsRequestPigeon {
      val itemsIds = pigeonVar_list[0] as List<Long?>
      val beforeItemWithId = pigeonVar_list[1] as Long?
      return QueueReorderItemsRequestPigeon(itemsIds, beforeItemWithId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      itemsIds,
      beforeItemWithId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is QueueReorderItemsRequestPigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Player position update
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlayerPositionUpdate (
  val progress: Long,
  val duration: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlayerPositionUpdate {
      val progress = pigeonVar_list[0] as Long
      val duration = pigeonVar_list[1] as Long
      return PlayerPositionUpdate(progress, duration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      progress,
      duration,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlayerPositionUpdate) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TextTrackStylePigeon (
  val backgroundColor: String? = null,
  val customData: Map<String, Any?>? = null,
  val edgeColor: String? = null,
  val fontFamily: String? = null,
  val fontGenericFamily: String? = null,
  val fontScale: Long? = null,
  val fontStyle: String? = null,
  val foregroundColor: String? = null,
  val windowColor: String? = null,
  val windowRoundedCornerRadius: Double? = null,
  val windowType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TextTrackStylePigeon {
      val backgroundColor = pigeonVar_list[0] as String?
      val customData = pigeonVar_list[1] as Map<String, Any?>?
      val edgeColor = pigeonVar_list[2] as String?
      val fontFamily = pigeonVar_list[3] as String?
      val fontGenericFamily = pigeonVar_list[4] as String?
      val fontScale = pigeonVar_list[5] as Long?
      val fontStyle = pigeonVar_list[6] as String?
      val foregroundColor = pigeonVar_list[7] as String?
      val windowColor = pigeonVar_list[8] as String?
      val windowRoundedCornerRadius = pigeonVar_list[9] as Double?
      val windowType = pigeonVar_list[10] as String?
      return TextTrackStylePigeon(backgroundColor, customData, edgeColor, fontFamily, fontGenericFamily, fontScale, fontStyle, foregroundColor, windowColor, windowRoundedCornerRadius, windowType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      backgroundColor,
      customData,
      edgeColor,
      fontFamily,
      fontGenericFamily,
      fontScale,
      fontStyle,
      foregroundColor,
      windowColor,
      windowRoundedCornerRadius,
      windowType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TextTrackStylePigeon) {
      return false
    }
    if (this === other) {
      return true
    }
    return RemoteMediaClientPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class RemoteMediaClientPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RepeatModePigeon.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaResumeStatePigeon.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaTrack.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LiveSeekableRange.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Volume.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaQueueItem.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaStatus.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueueLoadOptionsPigeon.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SeekOptionPigeon.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetPlaybackRateRequestPigeon.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoadMediaRequestPigeon.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueueLoadRequestPigeon.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueueInsertItemsRequestPigeon.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueueInsertItemAndPlayRequestPigeon.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueueReorderItemsRequestPigeon.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlayerPositionUpdate.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TextTrackStylePigeon.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RepeatModePigeon -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is MediaResumeStatePigeon -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is MediaTrack -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is LiveSeekableRange -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is MediaInfo -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is Volume -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is MediaQueueItem -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is MediaStatus -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is QueueLoadOptionsPigeon -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is SeekOptionPigeon -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is SetPlaybackRateRequestPigeon -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is LoadMediaRequestPigeon -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is QueueLoadRequestPigeon -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is QueueInsertItemsRequestPigeon -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is QueueInsertItemAndPlayRequestPigeon -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is QueueReorderItemsRequestPigeon -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is PlayerPositionUpdate -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is TextTrackStylePigeon -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RemoteMediaClientHostApi {
  fun loadMedia(request: LoadMediaRequestPigeon)
  fun queueLoadItems(request: QueueLoadRequestPigeon)
  fun queueInsertItems(request: QueueInsertItemsRequestPigeon)
  fun queueInsertItemAndPlay(request: QueueInsertItemAndPlayRequestPigeon)
  fun queueNextItem()
  fun queuePrevItem()
  fun queueJumpToItemWithId(itemId: Long)
  fun queueRemoveItemsWithIds(itemIds: List<Long?>)
  fun queueReorderItems(request: QueueReorderItemsRequestPigeon)
  fun seek(request: SeekOptionPigeon)
  fun setActiveTrackIds(trackIds: List<Long?>)
  fun setPlaybackRate(request: SetPlaybackRateRequestPigeon)
  fun setTextTrackStyle(textTrackStyle: TextTrackStylePigeon)
  fun play()
  fun pause()
  fun stop()

  companion object {
    /** The codec used by RemoteMediaClientHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      RemoteMediaClientPigeonPigeonCodec()
    }
    /** Sets up an instance of `RemoteMediaClientHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RemoteMediaClientHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.loadMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as LoadMediaRequestPigeon
            val wrapped: List<Any?> = try {
              api.loadMedia(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueLoadItems$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as QueueLoadRequestPigeon
            val wrapped: List<Any?> = try {
              api.queueLoadItems(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueInsertItems$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as QueueInsertItemsRequestPigeon
            val wrapped: List<Any?> = try {
              api.queueInsertItems(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueInsertItemAndPlay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as QueueInsertItemAndPlayRequestPigeon
            val wrapped: List<Any?> = try {
              api.queueInsertItemAndPlay(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueNextItem$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.queueNextItem()
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queuePrevItem$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.queuePrevItem()
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueJumpToItemWithId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.queueJumpToItemWithId(itemIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueRemoveItemsWithIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val itemIdsArg = args[0] as List<Long?>
            val wrapped: List<Any?> = try {
              api.queueRemoveItemsWithIds(itemIdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueReorderItems$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as QueueReorderItemsRequestPigeon
            val wrapped: List<Any?> = try {
              api.queueReorderItems(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.seek$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SeekOptionPigeon
            val wrapped: List<Any?> = try {
              api.seek(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setActiveTrackIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val trackIdsArg = args[0] as List<Long?>
            val wrapped: List<Any?> = try {
              api.setActiveTrackIds(trackIdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setPlaybackRate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SetPlaybackRateRequestPigeon
            val wrapped: List<Any?> = try {
              api.setPlaybackRate(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setTextTrackStyle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textTrackStyleArg = args[0] as TextTrackStylePigeon
            val wrapped: List<Any?> = try {
              api.setTextTrackStyle(textTrackStyleArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.play()
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              RemoteMediaClientPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class RemoteMediaClientFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by RemoteMediaClientFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      RemoteMediaClientPigeonPigeonCodec()
    }
  }
  fun onMediaStatusChanged(statusArg: MediaStatus?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onMediaStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RemoteMediaClientPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onQueueStatusChanged(queueItemsArg: List<MediaQueueItem?>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onQueueStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(queueItemsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RemoteMediaClientPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onPlayerPositionChanged(updateArg: PlayerPositionUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onPlayerPositionChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(RemoteMediaClientPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
