// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum RepeatModePigeon { off, all, single, allAndShuffle }

enum MediaResumeStatePigeon { play, pause, unchanged }

/// Media track information
class MediaTrack {
  MediaTrack({
    required this.trackId,
    required this.type,
    required this.trackContentId,
    required this.trackContentType,
    required this.subtype,
    required this.name,
    required this.language,
  });

  int trackId;

  int type;

  String trackContentId;

  String trackContentType;

  int subtype;

  String name;

  String language;

  List<Object?> _toList() {
    return <Object?>[
      trackId,
      type,
      trackContentId,
      trackContentType,
      subtype,
      name,
      language,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaTrack decode(Object result) {
    result as List<Object?>;
    return MediaTrack(
      trackId: result[0]! as int,
      type: result[1]! as int,
      trackContentId: result[2]! as String,
      trackContentType: result[3]! as String,
      subtype: result[4]! as int,
      name: result[5]! as String,
      language: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Live seekable range for live media streams
class LiveSeekableRange {
  LiveSeekableRange({
    required this.start,
    required this.end,
    required this.isMovingWindow,
    required this.isLiveDone,
  });

  int start;

  int end;

  bool isMovingWindow;

  bool isLiveDone;

  List<Object?> _toList() {
    return <Object?>[start, end, isMovingWindow, isLiveDone];
  }

  Object encode() {
    return _toList();
  }

  static LiveSeekableRange decode(Object result) {
    result as List<Object?>;
    return LiveSeekableRange(
      start: result[0]! as int,
      end: result[1]! as int,
      isMovingWindow: result[2]! as bool,
      isLiveDone: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LiveSeekableRange || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Media information including content and track details
class MediaInfo {
  MediaInfo({
    required this.contentId,
    required this.contentType,
    required this.streamType,
    required this.contentUrl,
    required this.duration,
    this.customData,
    this.tracks,
  });

  String contentId;

  String contentType;

  String streamType;

  String contentUrl;

  int duration;

  Map<String, Object?>? customData;

  List<MediaTrack?>? tracks;

  List<Object?> _toList() {
    return <Object?>[
      contentId,
      contentType,
      streamType,
      contentUrl,
      duration,
      customData,
      tracks,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaInfo decode(Object result) {
    result as List<Object?>;
    return MediaInfo(
      contentId: result[0]! as String,
      contentType: result[1]! as String,
      streamType: result[2]! as String,
      contentUrl: result[3]! as String,
      duration: result[4]! as int,
      customData: (result[5] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
      tracks: (result[6] as List<Object?>?)?.cast<MediaTrack?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Volume information
class Volume {
  Volume({required this.level, required this.muted});

  double level;

  bool muted;

  List<Object?> _toList() {
    return <Object?>[level, muted];
  }

  Object encode() {
    return _toList();
  }

  static Volume decode(Object result) {
    result as List<Object?>;
    return Volume(level: result[0]! as double, muted: result[1]! as bool);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Volume || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Media queue item
class MediaQueueItem {
  MediaQueueItem({
    required this.itemId,
    required this.preLoadTime,
    required this.startTime,
    required this.playbackDuration,
    this.media,
    required this.autoplay,
    this.activeTrackIds,
    this.customData,
  });

  int itemId;

  int preLoadTime;

  int startTime;

  int playbackDuration;

  MediaInfo? media;

  bool autoplay;

  List<int?>? activeTrackIds;

  Map<String, Object?>? customData;

  List<Object?> _toList() {
    return <Object?>[
      itemId,
      preLoadTime,
      startTime,
      playbackDuration,
      media,
      autoplay,
      activeTrackIds,
      customData,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaQueueItem decode(Object result) {
    result as List<Object?>;
    return MediaQueueItem(
      itemId: result[0]! as int,
      preLoadTime: result[1]! as int,
      startTime: result[2]! as int,
      playbackDuration: result[3]! as int,
      media: result[4] as MediaInfo?,
      autoplay: result[5]! as bool,
      activeTrackIds: (result[6] as List<Object?>?)?.cast<int?>(),
      customData: (result[7] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaQueueItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Complete media status
class MediaStatus {
  MediaStatus({
    required this.mediaSessionId,
    required this.playerState,
    required this.idleReason,
    required this.playbackRate,
    this.media,
    required this.volume,
    required this.repeatMode,
    required this.currentItemId,
    this.activeTrackIds,
    this.liveSeekableRange,
  });

  int mediaSessionId;

  String playerState;

  String idleReason;

  double playbackRate;

  MediaInfo? media;

  Volume volume;

  String repeatMode;

  int currentItemId;

  List<int?>? activeTrackIds;

  LiveSeekableRange? liveSeekableRange;

  List<Object?> _toList() {
    return <Object?>[
      mediaSessionId,
      playerState,
      idleReason,
      playbackRate,
      media,
      volume,
      repeatMode,
      currentItemId,
      activeTrackIds,
      liveSeekableRange,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaStatus decode(Object result) {
    result as List<Object?>;
    return MediaStatus(
      mediaSessionId: result[0]! as int,
      playerState: result[1]! as String,
      idleReason: result[2]! as String,
      playbackRate: result[3]! as double,
      media: result[4] as MediaInfo?,
      volume: result[5]! as Volume,
      repeatMode: result[6]! as String,
      currentItemId: result[7]! as int,
      activeTrackIds: (result[8] as List<Object?>?)?.cast<int?>(),
      liveSeekableRange: result[9] as LiveSeekableRange?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class QueueLoadOptionsPigeon {
  QueueLoadOptionsPigeon({
    required this.startIndex,
    required this.playPosition,
    required this.repeatMode,
    this.customData,
  });

  int startIndex;

  int playPosition;

  RepeatModePigeon repeatMode;

  Map<String, Object?>? customData;

  List<Object?> _toList() {
    return <Object?>[startIndex, playPosition, repeatMode, customData];
  }

  Object encode() {
    return _toList();
  }

  static QueueLoadOptionsPigeon decode(Object result) {
    result as List<Object?>;
    return QueueLoadOptionsPigeon(
      startIndex: result[0]! as int,
      playPosition: result[1]! as int,
      repeatMode: result[2]! as RepeatModePigeon,
      customData: (result[3] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! QueueLoadOptionsPigeon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class SeekOptionPigeon {
  SeekOptionPigeon({
    required this.position,
    required this.relative,
    required this.resumeState,
    required this.seekToInfinity,
  });

  int position;

  bool relative;

  MediaResumeStatePigeon resumeState;

  bool seekToInfinity;

  List<Object?> _toList() {
    return <Object?>[position, relative, resumeState, seekToInfinity];
  }

  Object encode() {
    return _toList();
  }

  static SeekOptionPigeon decode(Object result) {
    result as List<Object?>;
    return SeekOptionPigeon(
      position: result[0]! as int,
      relative: result[1]! as bool,
      resumeState: result[2]! as MediaResumeStatePigeon,
      seekToInfinity: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SeekOptionPigeon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class SetPlaybackRateRequestPigeon {
  SetPlaybackRateRequestPigeon({required this.rate});

  double rate;

  List<Object?> _toList() {
    return <Object?>[rate];
  }

  Object encode() {
    return _toList();
  }

  static SetPlaybackRateRequestPigeon decode(Object result) {
    result as List<Object?>;
    return SetPlaybackRateRequestPigeon(rate: result[0]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SetPlaybackRateRequestPigeon ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class LoadMediaRequestPigeon {
  LoadMediaRequestPigeon({
    required this.mediaInfo,
    required this.autoPlay,
    required this.playPosition,
    required this.playbackRate,
    this.activeTrackIds,
    this.credentials,
    this.credentialsType,
    this.customData,
  });

  MediaInfo mediaInfo;

  bool autoPlay;

  int playPosition;

  double playbackRate;

  List<int?>? activeTrackIds;

  String? credentials;

  String? credentialsType;

  Map<String, Object?>? customData;

  List<Object?> _toList() {
    return <Object?>[
      mediaInfo,
      autoPlay,
      playPosition,
      playbackRate,
      activeTrackIds,
      credentials,
      credentialsType,
      customData,
    ];
  }

  Object encode() {
    return _toList();
  }

  static LoadMediaRequestPigeon decode(Object result) {
    result as List<Object?>;
    return LoadMediaRequestPigeon(
      mediaInfo: result[0]! as MediaInfo,
      autoPlay: result[1]! as bool,
      playPosition: result[2]! as int,
      playbackRate: result[3]! as double,
      activeTrackIds: (result[4] as List<Object?>?)?.cast<int?>(),
      credentials: result[5] as String?,
      credentialsType: result[6] as String?,
      customData: (result[7] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LoadMediaRequestPigeon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class QueueLoadRequestPigeon {
  QueueLoadRequestPigeon({required this.items, this.options});

  List<MediaQueueItem?> items;

  QueueLoadOptionsPigeon? options;

  List<Object?> _toList() {
    return <Object?>[items, options];
  }

  Object encode() {
    return _toList();
  }

  static QueueLoadRequestPigeon decode(Object result) {
    result as List<Object?>;
    return QueueLoadRequestPigeon(
      items: (result[0] as List<Object?>?)!.cast<MediaQueueItem?>(),
      options: result[1] as QueueLoadOptionsPigeon?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! QueueLoadRequestPigeon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class QueueInsertItemsRequestPigeon {
  QueueInsertItemsRequestPigeon({required this.items, this.beforeItemWithId});

  List<MediaQueueItem?> items;

  int? beforeItemWithId;

  List<Object?> _toList() {
    return <Object?>[items, beforeItemWithId];
  }

  Object encode() {
    return _toList();
  }

  static QueueInsertItemsRequestPigeon decode(Object result) {
    result as List<Object?>;
    return QueueInsertItemsRequestPigeon(
      items: (result[0] as List<Object?>?)!.cast<MediaQueueItem?>(),
      beforeItemWithId: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! QueueInsertItemsRequestPigeon ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class QueueInsertItemAndPlayRequestPigeon {
  QueueInsertItemAndPlayRequestPigeon({
    required this.item,
    required this.beforeItemWithId,
  });

  MediaQueueItem item;

  int beforeItemWithId;

  List<Object?> _toList() {
    return <Object?>[item, beforeItemWithId];
  }

  Object encode() {
    return _toList();
  }

  static QueueInsertItemAndPlayRequestPigeon decode(Object result) {
    result as List<Object?>;
    return QueueInsertItemAndPlayRequestPigeon(
      item: result[0]! as MediaQueueItem,
      beforeItemWithId: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! QueueInsertItemAndPlayRequestPigeon ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class QueueReorderItemsRequestPigeon {
  QueueReorderItemsRequestPigeon({
    required this.itemsIds,
    this.beforeItemWithId,
  });

  List<int?> itemsIds;

  int? beforeItemWithId;

  List<Object?> _toList() {
    return <Object?>[itemsIds, beforeItemWithId];
  }

  Object encode() {
    return _toList();
  }

  static QueueReorderItemsRequestPigeon decode(Object result) {
    result as List<Object?>;
    return QueueReorderItemsRequestPigeon(
      itemsIds: (result[0] as List<Object?>?)!.cast<int?>(),
      beforeItemWithId: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! QueueReorderItemsRequestPigeon ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Player position update
class PlayerPositionUpdate {
  PlayerPositionUpdate({required this.progress, required this.duration});

  int progress;

  int duration;

  List<Object?> _toList() {
    return <Object?>[progress, duration];
  }

  Object encode() {
    return _toList();
  }

  static PlayerPositionUpdate decode(Object result) {
    result as List<Object?>;
    return PlayerPositionUpdate(
      progress: result[0]! as int,
      duration: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlayerPositionUpdate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class TextTrackStylePigeon {
  TextTrackStylePigeon({
    this.backgroundColor,
    this.customData,
    this.edgeColor,
    this.fontFamily,
    this.fontGenericFamily,
    this.fontScale,
    this.fontStyle,
    this.foregroundColor,
    this.windowColor,
    this.windowRoundedCornerRadius,
    this.windowType,
  });

  String? backgroundColor;

  Map<String, Object?>? customData;

  String? edgeColor;

  String? fontFamily;

  String? fontGenericFamily;

  int? fontScale;

  String? fontStyle;

  String? foregroundColor;

  String? windowColor;

  double? windowRoundedCornerRadius;

  String? windowType;

  List<Object?> _toList() {
    return <Object?>[
      backgroundColor,
      customData,
      edgeColor,
      fontFamily,
      fontGenericFamily,
      fontScale,
      fontStyle,
      foregroundColor,
      windowColor,
      windowRoundedCornerRadius,
      windowType,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TextTrackStylePigeon decode(Object result) {
    result as List<Object?>;
    return TextTrackStylePigeon(
      backgroundColor: result[0] as String?,
      customData: (result[1] as Map<Object?, Object?>?)
          ?.cast<String, Object?>(),
      edgeColor: result[2] as String?,
      fontFamily: result[3] as String?,
      fontGenericFamily: result[4] as String?,
      fontScale: result[5] as int?,
      fontStyle: result[6] as String?,
      foregroundColor: result[7] as String?,
      windowColor: result[8] as String?,
      windowRoundedCornerRadius: result[9] as double?,
      windowType: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TextTrackStylePigeon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is RepeatModePigeon) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is MediaResumeStatePigeon) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is MediaTrack) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is LiveSeekableRange) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is MediaInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is Volume) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is MediaQueueItem) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is MediaStatus) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is QueueLoadOptionsPigeon) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is SeekOptionPigeon) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is SetPlaybackRateRequestPigeon) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is LoadMediaRequestPigeon) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is QueueLoadRequestPigeon) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is QueueInsertItemsRequestPigeon) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is QueueInsertItemAndPlayRequestPigeon) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is QueueReorderItemsRequestPigeon) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is PlayerPositionUpdate) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is TextTrackStylePigeon) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RepeatModePigeon.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MediaResumeStatePigeon.values[value];
      case 131:
        return MediaTrack.decode(readValue(buffer)!);
      case 132:
        return LiveSeekableRange.decode(readValue(buffer)!);
      case 133:
        return MediaInfo.decode(readValue(buffer)!);
      case 134:
        return Volume.decode(readValue(buffer)!);
      case 135:
        return MediaQueueItem.decode(readValue(buffer)!);
      case 136:
        return MediaStatus.decode(readValue(buffer)!);
      case 137:
        return QueueLoadOptionsPigeon.decode(readValue(buffer)!);
      case 138:
        return SeekOptionPigeon.decode(readValue(buffer)!);
      case 139:
        return SetPlaybackRateRequestPigeon.decode(readValue(buffer)!);
      case 140:
        return LoadMediaRequestPigeon.decode(readValue(buffer)!);
      case 141:
        return QueueLoadRequestPigeon.decode(readValue(buffer)!);
      case 142:
        return QueueInsertItemsRequestPigeon.decode(readValue(buffer)!);
      case 143:
        return QueueInsertItemAndPlayRequestPigeon.decode(readValue(buffer)!);
      case 144:
        return QueueReorderItemsRequestPigeon.decode(readValue(buffer)!);
      case 145:
        return PlayerPositionUpdate.decode(readValue(buffer)!);
      case 146:
        return TextTrackStylePigeon.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RemoteMediaClientHostApi {
  /// Constructor for [RemoteMediaClientHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RemoteMediaClientHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> loadMedia(LoadMediaRequestPigeon request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.loadMedia$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueLoadItems(QueueLoadRequestPigeon request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueLoadItems$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueInsertItems(QueueInsertItemsRequestPigeon request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueInsertItems$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueInsertItemAndPlay(
    QueueInsertItemAndPlayRequestPigeon request,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueInsertItemAndPlay$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueNextItem() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueNextItem$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queuePrevItem() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queuePrevItem$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueJumpToItemWithId(int itemId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueJumpToItemWithId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[itemId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueRemoveItemsWithIds(List<int?> itemIds) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueRemoveItemsWithIds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[itemIds],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> queueReorderItems(QueueReorderItemsRequestPigeon request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.queueReorderItems$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> seek(SeekOptionPigeon request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.seek$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setActiveTrackIds(List<int?> trackIds) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setActiveTrackIds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[trackIds],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPlaybackRate(SetPlaybackRateRequestPigeon request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setPlaybackRate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setTextTrackStyle(TextTrackStylePigeon textTrackStyle) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.setTextTrackStyle$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textTrackStyle],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> play() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.play$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> pause() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.pause$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stop() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientHostApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class RemoteMediaClientFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onMediaStatusChanged(MediaStatus? status);

  void onQueueStatusChanged(List<MediaQueueItem?> queueItems);

  void onPlayerPositionChanged(PlayerPositionUpdate update);

  static void setUp(
    RemoteMediaClientFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onMediaStatusChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onMediaStatusChanged was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final MediaStatus? arg_status = (args[0] as MediaStatus?);
          try {
            api.onMediaStatusChanged(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onQueueStatusChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onQueueStatusChanged was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final List<MediaQueueItem?>? arg_queueItems =
              (args[0] as List<Object?>?)?.cast<MediaQueueItem?>();
          assert(
            arg_queueItems != null,
            'Argument for dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onQueueStatusChanged was null, expected non-null List<MediaQueueItem?>.',
          );
          try {
            api.onQueueStatusChanged(arg_queueItems!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onPlayerPositionChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onPlayerPositionChanged was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final PlayerPositionUpdate? arg_update =
              (args[0] as PlayerPositionUpdate?);
          assert(
            arg_update != null,
            'Argument for dev.flutter.pigeon.flutter_chrome_cast_platform_interface.RemoteMediaClientFlutterApi.onPlayerPositionChanged was null, expected non-null PlayerPositionUpdate.',
          );
          try {
            api.onPlayerPositionChanged(arg_update!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
